- type: latheRecipePack
  id: SecurityWeaponUpgrades
  recipes:
  - TerminusUpgradeHeatBlade
  - TerminusUpgradeAttackSpeed
  - TerminusUpgradeMeleeRange
  - SpearTelescopicUpgradeAttackSpeed
  - SpearTelescopicUpgradeMeleeRange