# SPDX-FileCopyrightText: 2026 Space Station 14 Contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antagCredits
  id: Traitor
  creditImage: /Textures/_Dumont/EndCredits/Antags/traitor.png

- type: antagCredits
  id: HeadRev
  creditImage: /Textures/_Dumont/EndCredits/Antags/revolution.png

- type: antagCredits
  id: Thief
  creditImage: /Textures/_Dumont/EndCredits/Antags/thief.png

- type: antagCredits
  id: Nukeops
  creditImage: /Textures/_Dumont/EndCredits/Antags/nukeops.png

- type: antagCredits
  id: Wizard
  creditImage: /Textures/_Dumont/EndCredits/Antags/wizard.png

- type: antagCredits
  id: Changeling
  creditImage: /Textures/_Dumont/EndCredits/Antags/changeling.png

- type: antagCredits
  id: Blob
  creditImage: /Textures/_Trauma/EndCredits/Antags/blob.png

- type: antagCredits
  id: Devil
  creditImage: /Textures/_Dumont/EndCredits/Antags/devil.png

- type: antagCredits
  id: AbductorAgentAntag
  creditImage: /Textures/_Dumont/EndCredits/Antags/abductors.png

- type: antagCredits
  id: CosmicAntagCultist
  creditImage: /Textures/_Dumont/EndCredits/Antags/cosmiccult.png

- type: antagCredits
  id: Heretic
  creditImage: /Textures/_Dumont/EndCredits/Antags/heretic.png

- type: antagCredits
  id: SpaceNinja
  creditImage: /Textures/_Dumont/EndCredits/Antags/ninja.png

- type: antagCredits
  id: ParadoxClone
  creditImage: /Textures/_Dumont/EndCredits/Antags/paradox.png

- type: antagCredits
  id: Xenomorph
  creditImage: /Textures/_Dumont/EndCredits/Antags/xenos.png

- type: antagCredits
  id: Zombie
  creditImage: /Textures/_Dumont/EndCredits/Antags/zombies.png

- type: antagCredits
  id: BloodCultist
  creditImage: /Textures/_Dumont/EndCredits/Antags/cult.png

- type: antagCredits
  id: Xenoborg
  creditImage: /Textures/_Dumont/EndCredits/Antags/xenoborgs.png

- type: antagCredits
  id: Slasher
  creditImage: /Textures/_Dumont/EndCredits/Antags/slasher.png

- type: antagCredits
  id: NukeopsMedic
  dontShowInCredits: true

- type: antagCredits
  id: NukeopsCommander
  dontShowInCredits: true

- type: antagCredits
  id: InitialInfected
  dontShowInCredits: true

- type: antagCredits
  id: GenericAntagonist
  dontShowInCredits: true

- type: antagCredits
  id: GenericTeamAntagonist
  dontShowInCredits: true

- type: antagCredits
  id: Ghoul
  dontShowInCredits: true
