// SPDX-FileCopyrightText: 2025 Space Station 14 Contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Chemistry;
using Content.Shared.Chemistry.Reagent;
using Content.Goobstation.Maths.FixedPoint;
using Content.Shared.Genetics;
using Content.Shared.Genetics.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using System.Numerics;
using System.Linq;

namespace Content.Client._Wega.Genetics.Ui;

[GenerateTypedNameReferences]
public sealed partial class DnaModifierWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IEntityNetworkManager _entNetworkManager = default!;
    [Dependency] private readonly IGameTiming _gameTiming = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private TimeSpan? _injectorCooldown;
    private TimeSpan? _subjectInjectCooldown;
    private bool _initializedBuffer = false;
    private bool _updateBuffer = false;
    private NetEntity _console;

    public DnaModifierWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // The combine view belongs between the data buffers and structural
        // enzymes, matching the laboratory workflow.
        var structuralTab = Tabs.GetChild(1);
        var combineTab = Tabs.GetChild(2);
        var transferTab = Tabs.GetChild(3);
        var rejuvenatorTab = Tabs.GetChild(4);
        Tabs.RemoveChild(structuralTab);
        Tabs.RemoveChild(combineTab);
        Tabs.RemoveChild(transferTab);
        Tabs.RemoveChild(rejuvenatorTab);
        Tabs.AddChild(structuralTab);
        Tabs.AddChild(combineTab);
        Tabs.AddChild(transferTab);
        Tabs.AddChild(rejuvenatorTab);

        Tabs.SetTabTitle(0, Loc.GetString("dna-modifier-tab-ui"));
        Tabs.SetTabTitle(1, Loc.GetString("dna-modifier-tab-se"));
        Tabs.SetTabTitle(2, Loc.GetString("dna-tab-combine"));
        Tabs.SetTabTitle(3, Loc.GetString("dna-modifier-tab-transfer"));
        Tabs.SetTabTitle(4, Loc.GetString("dna-modifier-tab-rejuvenator"));

        InitializeSequencingUi();
        EjectButton.OnPressed += _ => OnGeneticMessage?.Invoke(new DnaModifierConsoleEjectEvent(_console));
        FromDisk1.OnPressed += _ => OnExportFromDiskPressed(1);
        FromDisk2.OnPressed += _ => OnExportFromDiskPressed(2);
        FromDisk3.OnPressed += _ => OnExportFromDiskPressed(3);
        ClearButtonDisk.OnPressed += _ => OnGeneticMessage?.Invoke(new DnaModifierConsoleClearDiskEvent(_console));
        EjectRejuveButton.OnPressed += _ => OnGeneticMessage?.Invoke(new DnaModifierConsoleEjectRejuveEvent(_console));

        SubjectUI1.OnPressed += _ => OnButtonServerSavedPressed(1, 1);
        SubjectUISE1.OnPressed += _ => OnButtonServerSavedPressed(1, 2);
        SubjectSE1.OnPressed += _ => OnButtonServerSavedPressed(1, 3);
        SubjectUI2.OnPressed += _ => OnButtonServerSavedPressed(2, 1);
        SubjectUISE2.OnPressed += _ => OnButtonServerSavedPressed(2, 2);
        SubjectSE2.OnPressed += _ => OnButtonServerSavedPressed(2, 3);
        SubjectUI3.OnPressed += _ => OnButtonServerSavedPressed(3, 1);
        SubjectUISE3.OnPressed += _ => OnButtonServerSavedPressed(3, 2);
        SubjectSE3.OnPressed += _ => OnButtonServerSavedPressed(3, 3);

        ClearButton1.OnPressed += _ => OnClearBufferPressed(1);
        ClearButton2.OnPressed += _ => OnClearBufferPressed(2);
        ClearButton3.OnPressed += _ => OnClearBufferPressed(3);
        RenameButton1.OnPressed += _ => OnRenameBufferPressed(1);
        RenameButton2.OnPressed += _ => OnRenameBufferPressed(2);
        RenameButton3.OnPressed += _ => OnRenameBufferPressed(3);
        ExportButton1.OnPressed += _ => OnExportOnDiskPressed(1);
        ExportButton2.OnPressed += _ => OnExportOnDiskPressed(2);
        ExportButton3.OnPressed += _ => OnExportOnDiskPressed(3);
    }

    private DnaModifierBoundUserInterfaceState? _lastUpdate;
    public void UpdateState(DnaModifierBoundUserInterfaceState state)
    {
        _lastUpdate = state;
        _console = state.Console;
        var console = _entManager.GetEntity(_console);


        // Upper state


        if (!string.IsNullOrWhiteSpace(state.ScannerBodyInfo))
        {
            NameLabel.Text = state.ScannerBodyInfo;
            StatusLabel.Text = state.ScannerBodyStatus;
            SpeciesLabel.Text = string.IsNullOrWhiteSpace(state.ScannerSpecies) ? Loc.GetString("dna-modifier-no-data") : state.ScannerSpecies;
            EjectButton.Disabled = false;
            AppearancePreview.Visible = state.ScannerBody is not null;
            if (state.ScannerBody is { } body && _entManager.TryGetEntity(body, out var bodyEntity) && bodyEntity is { } bodyUid)
                SetScannerPreview(bodyUid);
        }
        else
        {
            NameLabel.Text = Loc.GetString("dna-modifier-no-data");
            StatusLabel.Text = Loc.GetString("dna-modifier-no-data");
            SpeciesLabel.Text = Loc.GetString("dna-modifier-no-data");
            EjectButton.Disabled = true;
            AppearancePreview.Visible = false;
            ClearScannerPreview();

            DisabledSubjectDiskBlock(null);
        }

        HealthBar.Value = state.ScannerBodyHealth;
        RadiationBar.Value = state.ScannerBodyRadiation;

        UpdateHealthBarColor(state.ScannerBodyHealth);

        UniqueEnzymesLabel.Text = string.IsNullOrWhiteSpace(state.ScannerBodyDna)
            ? Loc.GetString("dna-modifier-no-data")
            : state.ScannerBodyDna;

        // Lower state

        _injectorCooldown = state.InjectorCooldownRemaining > TimeSpan.Zero
            ? _gameTiming.CurTime + state.InjectorCooldownRemaining
            : null;

        _subjectInjectCooldown = state.SubjectInjectCooldownRemaining > TimeSpan.Zero
            ? _gameTiming.CurTime + state.SubjectInjectCooldownRemaining
            : null;

        UpdateSequencingUi(state);

        // Buffer & Disk
        if (!_initializedBuffer)
        {
            BufferContainer1.RemoveAllChildren();
            BufferContainer2.RemoveAllChildren();
            BufferContainer3.RemoveAllChildren();
            InitializeBufferData(state.Buffers);
        }
        else if (_updateBuffer)
        {
            _updateBuffer = false;
            _initializedBuffer = false;
            BufferContainer1.RemoveAllChildren();
            BufferContainer2.RemoveAllChildren();
            BufferContainer3.RemoveAllChildren();
            InitializeBufferData(state.Buffers);
        }

        EjectButtonDisk.Disabled = state.HasDisk ? false : true;

        FromDisk1.Disabled = state.HasDisk ? false : true;
        FromDisk2.Disabled = state.HasDisk ? false : true;
        FromDisk3.Disabled = state.HasDisk ? false : true;

        ClearButtonDisk.Disabled = state.HasDisk ? false : true;


        UpdateDiskContainer(state.Enzyme);

        // Rejuve
        RejuveContainer.RemoveAllChildren();
        CreateBeakerUI(RejuveContainer, state.InputContainerInfo);
        EjectRejuveButton.Disabled = state.ScannerHasBeaker ? false : true;

    }

    private void UpdateHealthBarColor(float health)
    {
        if (HealthBar == null)
            return;

        var normalizedHealth = health / HealthBar.MaxValue;

        const float leftHue = 0.0f;
        const float middleHue = 0.066f;
        const float rightHue = 0.33f;
        const float saturation = 1.0f;
        const float value = 0.8f;
        const float alpha = 1.0f;

        const float leftSideSize = 0.5f;
        const float rightSideSize = 0.5f;

        float finalHue;
        if (normalizedHealth <= leftSideSize)
        {
            normalizedHealth /= leftSideSize;
            finalHue = MathHelper.Lerp(leftHue, middleHue, normalizedHealth);
        }
        else
        {
            normalizedHealth = (normalizedHealth - leftSideSize) / rightSideSize;
            finalHue = MathHelper.Lerp(middleHue, rightHue, normalizedHealth);
        }

        HealthBar.ForegroundStyleBoxOverride ??= new StyleBoxFlat();

        var foregroundStyleBoxOverride = (StyleBoxFlat)HealthBar.ForegroundStyleBoxOverride;
        foregroundStyleBoxOverride.BackgroundColor =
            Color.FromHsv(new Vector4(finalHue, saturation, value, alpha));
    }

    private void InitializeBufferData(Dictionary<int, EnzymeInfo?> buffers)
    {
        _initializedBuffer = true;

        for (int bufferIndex = 1; bufferIndex <= 3; bufferIndex++)
        {
            if (buffers.TryGetValue(bufferIndex, out var data) && data != null)
            {
                var bufferContainer = CreateBufferContainer(data, bufferIndex);
                var targetContainer = bufferIndex switch
                {
                    1 => BufferContainer1,
                    2 => BufferContainer2,
                    3 => BufferContainer3,
                    _ => null
                };

                if (targetContainer != null)
                {
                    targetContainer.AddChild(bufferContainer);
                    EnableBufferBlock(bufferIndex);
                    DisabledSubjectDiskBlock(bufferIndex);
                }
            }
            else
            {
                var bufferLabel = new Label { Text = Loc.GetString("dna-modifier-button-no-buffer") };
                var targetContainer = bufferIndex switch
                {
                    1 => BufferContainer1,
                    2 => BufferContainer2,
                    3 => BufferContainer3,
                    _ => null
                };

                targetContainer?.AddChild(bufferLabel);
            }
        }
    }

    private BoxContainer CreateBufferContainer(EnzymeInfo data, int bufferIndex)
    {
        var sampleName = data.SampleName;
        var bufferContainer = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };

        // Name Container
        var nameContainer = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
        nameContainer.AddChild(new Label { Text = Loc.GetString("dna-modifier-label-sample-name"), MinWidth = 40 });
        nameContainer.AddChild(new Control { MinWidth = 25 });
        nameContainer.AddChild(new Label { Text = sampleName });

        // Data Container
        var dataContainer = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
        dataContainer.AddChild(new Label { Text = Loc.GetString("dna-modifier-label-data"), MinWidth = 40 });
        dataContainer.AddChild(new Control { MinWidth = 25 });

        var dataLabel = new Label();
        bool hasUniqueIdentifiers = data.Identifier != null;
        bool hasStructuralEnzymes = data.Info != null && data.Info.Count > 0;

        dataLabel.Text = (hasUniqueIdentifiers, hasStructuralEnzymes) switch
        {
            (true, true) => Loc.GetString("dna-modifier-label-both-prototypes"),
            (true, false) => Loc.GetString("dna-modifier-label-unique-identifiers"),
            (false, true) => Loc.GetString("dna-modifier-label-structural-enzymes"),
            _ => Loc.GetString("dna-modifier-label-no-prototypes")
        };

        dataContainer.AddChild(dataLabel);

        // Buttons Container
        var buttonsContainer = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
        buttonsContainer.AddChild(new Label { Text = Loc.GetString("dna-modifier-label-actions"), MinWidth = 40 });
        buttonsContainer.AddChild(new Control { MinWidth = 25 });

        // Injector Button
        var injectorButton = new Button
        {
            Name = "InjectorButton",
            Text = Loc.GetString("dna-modifier-button-injector"),
            Disabled = _injectorCooldown.HasValue && _gameTiming.CurTime < _injectorCooldown
        };
        injectorButton.OnPressed += _ => OnInjectorPressed(bufferIndex, injectorButton);
        buttonsContainer.AddChild(injectorButton);

        // Block Inject Button
        if (hasStructuralEnzymes)
        {
            var blockSelectButton = new OptionButton
            {
                MinWidth = 40,
                StyleClasses = { StyleNano.ButtonOpenRight }
            };
            foreach (var gene in data.Info!)
                blockSelectButton.AddItem($"{gene.Order}", gene.Order);
            blockSelectButton.SelectId(1);
            blockSelectButton.OnItemSelected += args => blockSelectButton.SelectId(args.Id);

            var injectBlockButton = new Button
            {
                Text = Loc.GetString("dna-modifier-button-inject-block"),
                StyleClasses = { StyleNano.ButtonOpenLeft },
                Disabled = _injectorCooldown.HasValue && _gameTiming.CurTime < _injectorCooldown
            };
            injectBlockButton.OnPressed += _ => OnInjectBlockPressed(bufferIndex, injectBlockButton, blockSelectButton.SelectedId);

            buttonsContainer.AddChild(blockSelectButton);
            buttonsContainer.AddChild(injectBlockButton);
        }

        // Subject Inject Button
        var subjectInjectButton = new Button
        {
            Name = "SubjectInjectButton",
            Text = Loc.GetString("dna-modifier-button-subject-inject"),
            Disabled = _subjectInjectCooldown.HasValue && _gameTiming.CurTime < _subjectInjectCooldown
        };
        subjectInjectButton.OnPressed += _ =>
        {
            OnSubjectInjectPressed(bufferIndex, subjectInjectButton);
        };
        buttonsContainer.AddChild(subjectInjectButton);

        if (data.Identifier != null)
        {
            var fields = new OptionButton();
            var identifiers = AppearanceGene.Fields.ToList();
            for (var i = 0; i < identifiers.Count; i++)
                fields.AddItem(Loc.GetString("dna-eu-" + identifiers[i]), i);
            fields.OnItemSelected += args => fields.SelectId(args.Id);
            var applyField = new Button { Text = Loc.GetString("dna-eu-apply-block") };
            applyField.OnPressed += _ => OnGeneticMessage?.Invoke(new GeneticBufferAppearanceMessage(bufferIndex, identifiers[fields.SelectedId]));
            bufferContainer.AddChild(new BoxContainer { Children = { fields, applyField } });
        }

        // Assemble container
        bufferContainer.AddChild(nameContainer);
        bufferContainer.AddChild(dataContainer);
        bufferContainer.AddChild(buttonsContainer);

        return bufferContainer;
    }

    private void UpdateDiskContainer(EnzymeInfo? enzyme)
    {
        DiskContainer.RemoveAllChildren();
        if (enzyme == null)
        {
            DiskContainer.AddChild(new Label
            {
                Text = Loc.GetString("dna-modifier-no-disk")
            });
            return;
        }

        var bufferContainer = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };

        // Name Container
        var nameContainer = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
        nameContainer.AddChild(new Label
        {
            Text = Loc.GetString("dna-modifier-label-sample-name"),
            MinWidth = 40
        });
        nameContainer.AddChild(new Control { MinWidth = 25 });
        nameContainer.AddChild(new Label
        {
            Text = enzyme.SampleName
        });

        // Data Container
        var dataContainer = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
        dataContainer.AddChild(new Label
        {
            Text = Loc.GetString("dna-modifier-label-data"),
            MinWidth = 40
        });
        dataContainer.AddChild(new Control { MinWidth = 25 });

        var dataLabel = new Label();
        bool hasUniqueIdentifiers = enzyme.Identifier != null;
        bool hasStructuralEnzymes = enzyme.Info != null && enzyme.Info.Count > 0;

        dataLabel.Text = (hasUniqueIdentifiers, hasStructuralEnzymes) switch
        {
            (true, true) => Loc.GetString("dna-modifier-label-both-prototypes"),
            (true, false) => Loc.GetString("dna-modifier-label-unique-identifiers"),
            (false, true) => Loc.GetString("dna-modifier-label-structural-enzymes"),
            _ => Loc.GetString("dna-modifier-label-no-prototypes")
        };

        dataContainer.AddChild(dataLabel);

        // Assemble container
        bufferContainer.AddChild(nameContainer);
        bufferContainer.AddChild(dataContainer);
        DiskContainer.AddChild(bufferContainer);
    }

    private void OnButtonServerSavedPressed(int section, int type)
    {
        _updateBuffer = true;
        OnGeneticMessage?.Invoke(
            new DnaModifierConsoleSaveServerEvent(_console, section, type));
    }

    private void OnInjectorPressed(int index, Button button)
    {
        _updateBuffer = true;
        button.Disabled = true;
        OnGeneticMessage?.Invoke(
            new DnaModifierConsoleInjectorEvent(_console, index));
    }

    private void OnInjectBlockPressed(int bufferIndex, Button button, int blockId)
    {
        _updateBuffer = true;
        button.Disabled = true;
        OnGeneticMessage?.Invoke(
            new DnaModifierInjectBlockEvent(_console, bufferIndex, blockId));
    }

    private void OnSubjectInjectPressed(int index, Button button)
    {
        _updateBuffer = true;
        button.Disabled = true;
        OnGeneticMessage?.Invoke(
            new DnaModifierConsoleSubjectInjectEvent(_console, index));
    }

    private void OnClearBufferPressed(int index)
    {
        _updateBuffer = true;
        OnGeneticMessage?.Invoke(
            new DnaModifierConsoleClearBufferEvent(_console, index));
    }

    private void OnRenameBufferPressed(int index)
    {
        _updateBuffer = true;
        var session = IoCManager.Resolve<IPlayerManager>().LocalSession;
        if (session?.AttachedEntity.HasValue == true)
        {
            var user = _entManager.GetNetEntity(session.AttachedEntity.Value);
            OnGeneticMessage?.Invoke(
                new DnaModifierConsoleRenameBufferEvent(_console, user, index));
        }
    }

    private void OnExportOnDiskPressed(int index)
    {
        OnGeneticMessage?.Invoke(
            new DnaModifierConsoleExportOnDiskEvent(_console, index));
    }

    private void OnExportFromDiskPressed(int index)
    {
        OnGeneticMessage?.Invoke(
            new DnaModifierConsoleExportFromDiskEvent(_console, index));
    }

    #region Initilize Disk
    private void EnableBufferBlock(int bufferIndex)
    {
        switch (bufferIndex)
        {
            case 1:
                ClearButton1.Disabled = false;
                RenameButton1.Disabled = false;
                ExportButton1.Disabled = false;
                break;
            case 2:
                ClearButton2.Disabled = false;
                RenameButton2.Disabled = false;
                ExportButton2.Disabled = false;
                break;
            case 3:
                ClearButton3.Disabled = false;
                RenameButton3.Disabled = false;
                ExportButton3.Disabled = false;
                break;
            default: break;
        }
    }

    private void DisabledSubjectDiskBlock(int? bufferIndex)
    {
        if (bufferIndex != null)
        {
            switch (bufferIndex)
            {
                case 1:
                    SubjectUI1.Disabled = true;
                    SubjectUISE1.Disabled = true;
                    SubjectSE1.Disabled = true;
                    break;
                case 2:
                    SubjectUI2.Disabled = true;
                    SubjectUISE2.Disabled = true;
                    SubjectSE2.Disabled = true;
                    break;
                case 3:
                    SubjectUI3.Disabled = true;
                    SubjectUISE3.Disabled = true;
                    SubjectSE3.Disabled = true;
                    break;
                default: break;
            }
        }
        else
        {
            SubjectUI1.Disabled = true;
            SubjectUISE1.Disabled = true;
            SubjectSE1.Disabled = true;
            SubjectUI2.Disabled = true;
            SubjectUISE2.Disabled = true;
            SubjectSE2.Disabled = true;
            SubjectUI3.Disabled = true;
            SubjectUISE3.Disabled = true;
            SubjectSE3.Disabled = true;
        }
    }
    #endregion

    #region Initilize Rejuve
    private void CreateBeakerUI(Control control, ContainerInfo? info)
    {
        control.RemoveAllChildren();

        if (info == null)
        {
            control.AddChild(new Label
            {
                Text = Loc.GetString("dna-modifier-no-container-loaded-text")
            });
            return;
        }

        control.AddChild(new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Children =
            {
                new Label { Text = $"{info.DisplayName}: " },
                new Label
                {
                    Text = $"{info.CurrentVolume}/{info.MaxVolume}",
                    StyleClasses = { StyleNano.StyleClassLabelSecondaryColor }
                }
            }
        });

        var rowCount = 0;
        if (info.Reagents != null)
        {
            foreach (var reagent in info.Reagents)
            {
                _prototypeManager.TryIndex(reagent.Reagent.Prototype, out ReagentPrototype? proto);
                var name = proto?.LocalizedName ?? Loc.GetString("dna-modifier-unknown-reagent-text");
                var reagentColor = proto?.SubstanceColor ?? default(Color);

                control.AddChild(BuildReagentRow(reagentColor, rowCount++, name, reagent.Reagent, reagent.Quantity, true));
            }
        }
    }

    private Control BuildReagentRow(Color reagentColor, int rowCount, string name, ReagentId reagent, FixedPoint2 quantity, bool addReagentButtons)
    {
        var rowColor1 = Color.FromHex("#1B1B1E");
        var rowColor2 = Color.FromHex("#202025");
        var currentRowColor = (rowCount % 2 == 1) ? rowColor1 : rowColor2;

        if (reagentColor == default(Color) || !addReagentButtons)
        {
            reagentColor = currentRowColor;
        }

        var reagentButtons = CreateReagentTransferButtons(reagent, addReagentButtons);
        var rowContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Children =
            {
                new Label { Text = $"{name}: " },
                new Label
                {
                    Text = $"{quantity}u",
                    StyleClasses = { StyleNano.StyleClassLabelSecondaryColor }
                },
                new Control { HorizontalExpand = true },
                new PanelContainer
                {
                    Name = "colorPanel",
                    VerticalExpand = true,
                    MinWidth = 4,
                    PanelOverride = new StyleBoxFlat
                    {
                        BackgroundColor = reagentColor
                    },
                    Margin = new Thickness(0, 1)
                }
            }
        };

        foreach (var reagentButton in reagentButtons)
        {
            rowContainer.AddChild(reagentButton);
        }

        return new PanelContainer
        {
            PanelOverride = new StyleBoxFlat(currentRowColor),
            Children = { rowContainer }
        };
    }

    private List<ReagentButton> CreateReagentTransferButtons(ReagentId reagent, bool addReagentButtons)
    {
        if (!addReagentButtons) return new List<ReagentButton>();

        var buttonConfigs = new (string text, DnaModifierReagentAmount amount, string styleClass)[]
        {
            ("1", DnaModifierReagentAmount.U1, StyleBase.ButtonOpenBoth),
            ("5", DnaModifierReagentAmount.U5, StyleBase.ButtonOpenBoth),
            ("10", DnaModifierReagentAmount.U10, StyleBase.ButtonOpenBoth),
            ("25", DnaModifierReagentAmount.U25, StyleBase.ButtonOpenBoth),
            ("50", DnaModifierReagentAmount.U50, StyleBase.ButtonOpenBoth),
            ("100", DnaModifierReagentAmount.U100, StyleBase.ButtonOpenBoth),
            ("All", DnaModifierReagentAmount.All, StyleBase.ButtonOpenLeft),
        };

        var buttons = new List<ReagentButton>();
        foreach (var (text, amount, styleClass) in buttonConfigs)
        {
            var reagentTransferButton = new ReagentButton(text, amount, reagent, styleClass);
            reagentTransferButton.OnPressed += args =>
            {
                OnGeneticMessage?.Invoke(
                    new DnaModifierConsoleReagentButtonEvent(_console, amount, reagent));
            };
            buttons.Add(reagentTransferButton);
        }

        return buttons;
    }

    private sealed class ReagentButton : Button
    {
        public DnaModifierReagentAmount Amount { get; set; }
        public ReagentId Id { get; set; }

        public ReagentButton(string text, DnaModifierReagentAmount amount, ReagentId id, string styleClass)
        {
            AddStyleClass(styleClass);
            Text = text;
            Amount = amount;
            Id = id;
        }
    }
    #endregion
}
